export interface Resource {
  title: string;
  url: string;
  type: 'article' | 'video' | 'course' | 'documentation' | 'paper';
}

export interface Node {
  id: string;
  title: string;
  description: string;
  tier: 1 | 2 | 3;
  resources: Resource[];
  color?: string;
}

export interface Link {
  source: string;
  target: string;
}

// Helper function to generate random resources
const generateResources = (count: number = 1): Resource[] => {
  const types: Resource['type'][] = ['article', 'video', 'course', 'documentation', 'paper'];
  return Array.from({ length: count }, (_, i) => ({
    title: `Resource ${i + 1}`,
    url: `https://example.com/resource-${i + 1}`,
    type: types[Math.floor(Math.random() * types.length)],
  }));
};

export const nodes: Node[] = [
  // Tier 1: Major categories (15 nodes)
  {
    id: 'ml',
    title: 'Machine Learning',
    description: 'The field of study that gives computers the ability to learn without being explicitly programmed.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(2),
  },
  {
    id: 'python',
    title: 'Python',
    description: 'A high-level programming language widely used in data science and machine learning.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'stats',
    title: 'Statistics',
    description: 'The study of the collection, analysis, interpretation, and presentation of data.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'deep-learning',
    title: 'Deep Learning',
    description: 'A subset of machine learning using neural networks with multiple layers.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(2),
  },
  {
    id: 'data-viz',
    title: 'Data Visualization',
    description: 'The graphical representation of information and data using visual elements.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'big-data',
    title: 'Big Data',
    description: 'Extremely large datasets that require special tools and techniques to process.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'cloud',
    title: 'Cloud Computing',
    description: 'Delivery of computing services over the internet including storage and processing.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'database',
    title: 'Database',
    description: 'Organized collection of structured information stored electronically.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'data-eng',
    title: 'Data Engineering',
    description: 'Building systems for collecting, storing, and analyzing data at scale.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'nlp',
    title: 'Natural Language Processing',
    description: 'AI field focused on the interaction between computers and human language.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(2),
  },
  {
    id: 'cv',
    title: 'Computer Vision',
    description: 'Field of AI that trains computers to interpret and understand visual information.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(2),
  },
  {
    id: 'time-series',
    title: 'Time Series',
    description: 'Sequence of data points collected over time intervals.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'rl',
    title: 'Reinforcement Learning',
    description: 'Machine learning paradigm where agents learn by interacting with an environment.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(2),
  },
  {
    id: 'math',
    title: 'Mathematics',
    description: 'Fundamental mathematical concepts essential for data science.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },
  {
    id: 'r',
    title: 'R',
    description: 'Programming language and environment for statistical computing and graphics.',
    tier: 1,
    color: '#00ffff',
    resources: generateResources(1),
  },

  // Tier 2: Sub-categories (35 nodes)
  {
    id: 'supervised',
    title: 'Supervised Learning',
    description: 'A type of machine learning where the model is trained on labeled data.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'unsupervised',
    title: 'Unsupervised Learning',
    description: 'A type of machine learning that finds patterns in data without labeled examples.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'pandas',
    title: 'Pandas',
    description: 'A powerful data manipulation and analysis library for Python.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'numpy',
    title: 'NumPy',
    description: 'A fundamental package for scientific computing with Python.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'matplotlib',
    title: 'Matplotlib',
    description: 'A comprehensive library for creating static and interactive visualizations.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'seaborn',
    title: 'Seaborn',
    description: 'Statistical data visualization library built on matplotlib.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'plotly',
    title: 'Plotly',
    description: 'Interactive graphing library for making publication-quality graphs.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'tensorflow',
    title: 'TensorFlow',
    description: 'Open-source platform for machine learning and deep learning.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'pytorch',
    title: 'PyTorch',
    description: 'Open-source machine learning framework based on Torch library.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'keras',
    title: 'Keras',
    description: 'High-level neural networks API written in Python.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'spark',
    title: 'Apache Spark',
    description: 'Unified analytics engine for large-scale data processing.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'hadoop',
    title: 'Hadoop',
    description: 'Framework for distributed storage and processing of big data.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'aws',
    title: 'AWS',
    description: 'Amazon Web Services cloud computing platform.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'gcp',
    title: 'Google Cloud',
    description: 'Google Cloud Platform for cloud computing services.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'azure',
    title: 'Azure',
    description: 'Microsoft cloud computing platform and services.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'sql',
    title: 'SQL',
    description: 'Structured Query Language for managing relational databases.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'mongodb',
    title: 'MongoDB',
    description: 'NoSQL document database for modern applications.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'postgresql',
    title: 'PostgreSQL',
    description: 'Advanced open-source relational database system.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'airflow',
    title: 'Apache Airflow',
    description: 'Platform to programmatically author, schedule, and monitor workflows.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'kafka',
    title: 'Apache Kafka',
    description: 'Distributed event streaming platform for real-time data feeds.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'docker',
    title: 'Docker',
    description: 'Platform for developing, shipping, and running applications in containers.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'kubernetes',
    title: 'Kubernetes',
    description: 'Container orchestration platform for automating deployment and scaling.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'feature-eng',
    title: 'Feature Engineering',
    description: 'Process of creating new features from existing data to improve model performance.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'model-eval',
    title: 'Model Evaluation',
    description: 'Process of assessing the performance of machine learning models.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'data-prep',
    title: 'Data Preprocessing',
    description: 'Transforming raw data into a format suitable for analysis and modeling.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'cnn',
    title: 'Convolutional Neural Networks',
    description: 'Deep learning architecture particularly effective for image recognition.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'rnn',
    title: 'Recurrent Neural Networks',
    description: 'Neural networks designed to handle sequential data.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'transformer',
    title: 'Transformers',
    description: 'Deep learning architecture that has revolutionized NLP.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'bert',
    title: 'BERT',
    description: 'Bidirectional Encoder Representations from Transformers for NLP.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'gpt',
    title: 'GPT',
    description: 'Generative Pre-trained Transformer models for language tasks.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'opencv',
    title: 'OpenCV',
    description: 'Open-source computer vision and machine learning software library.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'yolo',
    title: 'YOLO',
    description: 'You Only Look Once - real-time object detection algorithm.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'lstm',
    title: 'LSTM',
    description: 'Long Short-Term Memory networks for sequence prediction.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },
  {
    id: 'gan',
    title: 'GANs',
    description: 'Generative Adversarial Networks for generating synthetic data.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(2),
  },
  {
    id: 'autoencoder',
    title: 'Autoencoders',
    description: 'Neural networks used for unsupervised learning and dimensionality reduction.',
    tier: 2,
    color: '#ff00ff',
    resources: generateResources(1),
  },

  // Tier 3: Specific tools/concepts (50 nodes)
  {
    id: 'lightgbm',
    title: 'LightGBM',
    description: 'A gradient boosting framework that uses tree based learning algorithms.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(2),
  },
  {
    id: 'xgboost',
    title: 'XGBoost',
    description: 'An optimized distributed gradient boosting library designed to be highly efficient.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'optuna',
    title: 'Optuna',
    description: 'An automatic hyperparameter optimization software framework.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(2),
  },
  {
    id: 'sklearn',
    title: 'Scikit-learn',
    description: 'A machine learning library for Python built on NumPy, SciPy, and matplotlib.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'catboost',
    title: 'CatBoost',
    description: 'Gradient boosting library with categorical features support.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'random-forest',
    title: 'Random Forest',
    description: 'Ensemble learning method using multiple decision trees.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'svm',
    title: 'SVM',
    description: 'Support Vector Machine for classification and regression.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'kmeans',
    title: 'K-Means',
    description: 'Clustering algorithm that partitions data into k clusters.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'pca',
    title: 'PCA',
    description: 'Principal Component Analysis for dimensionality reduction.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'linear-reg',
    title: 'Linear Regression',
    description: 'Statistical method for modeling relationships between variables.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'logistic-reg',
    title: 'Logistic Regression',
    description: 'Statistical model for binary classification problems.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'decision-tree',
    title: 'Decision Tree',
    description: 'Tree-like model for decision making and classification.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'naive-bayes',
    title: 'Naive Bayes',
    description: 'Probabilistic classifier based on Bayes theorem.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'knn',
    title: 'K-NN',
    description: 'K-Nearest Neighbors algorithm for classification and regression.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'dbscan',
    title: 'DBSCAN',
    description: 'Density-based clustering algorithm for finding clusters of arbitrary shape.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'hierarchical',
    title: 'Hierarchical Clustering',
    description: 'Clustering method that builds a hierarchy of clusters.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'tsne',
    title: 't-SNE',
    description: 't-Distributed Stochastic Neighbor Embedding for visualization.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'umap',
    title: 'UMAP',
    description: 'Uniform Manifold Approximation and Projection for dimensionality reduction.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'cross-val',
    title: 'Cross Validation',
    description: 'Technique for assessing model performance and generalization.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'grid-search',
    title: 'Grid Search',
    description: 'Hyperparameter tuning technique that exhaustively searches parameter space.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'bayesian-opt',
    title: 'Bayesian Optimization',
    description: 'Probabilistic approach to global optimization of expensive functions.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'roc-auc',
    title: 'ROC-AUC',
    description: 'Receiver Operating Characteristic - Area Under Curve metric.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'f1-score',
    title: 'F1 Score',
    description: 'Harmonic mean of precision and recall for classification evaluation.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'confusion-matrix',
    title: 'Confusion Matrix',
    description: 'Table used to evaluate the performance of classification models.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'normalization',
    title: 'Normalization',
    description: 'Scaling technique to bring data to a common scale.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'standardization',
    title: 'Standardization',
    description: 'Scaling technique to transform data to have zero mean and unit variance.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'one-hot',
    title: 'One-Hot Encoding',
    description: 'Categorical encoding technique for converting categories to binary vectors.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'label-encoding',
    title: 'Label Encoding',
    description: 'Converting categorical labels into numeric form.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'missing-data',
    title: 'Missing Data Handling',
    description: 'Techniques for dealing with missing values in datasets.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'outlier-detection',
    title: 'Outlier Detection',
    description: 'Identifying and handling anomalous data points.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'feature-selection',
    title: 'Feature Selection',
    description: 'Process of selecting relevant features for model training.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'feature-scaling',
    title: 'Feature Scaling',
    description: 'Normalizing the range of independent features.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'arima',
    title: 'ARIMA',
    description: 'AutoRegressive Integrated Moving Average for time series forecasting.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'prophet',
    title: 'Prophet',
    description: 'Facebook time series forecasting tool.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'lstm-ts',
    title: 'LSTM for Time Series',
    description: 'Using LSTM networks for time series prediction.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'q-learning',
    title: 'Q-Learning',
    description: 'Model-free reinforcement learning algorithm.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'policy-gradient',
    title: 'Policy Gradient',
    description: 'Reinforcement learning method that optimizes policy directly.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'actor-critic',
    title: 'Actor-Critic',
    description: 'Reinforcement learning algorithm combining value and policy methods.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'dqn',
    title: 'DQN',
    description: 'Deep Q-Network for reinforcement learning with neural networks.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'nltk',
    title: 'NLTK',
    description: 'Natural Language Toolkit for Python NLP.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'spacy',
    title: 'spaCy',
    description: 'Advanced NLP library for Python.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'word2vec',
    title: 'Word2Vec',
    description: 'Technique for learning word embeddings.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'glove',
    title: 'GloVe',
    description: 'Global Vectors for word representation.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
  {
    id: 'fasttext',
    title: 'FastText',
    description: 'Library for efficient text classification and word representation.',
    tier: 3,
    color: '#ffff00',
    resources: generateResources(1),
  },
];

// Generate links between nodes
export const links: Link[] = [
  // Tier 1 to Tier 2 connections
  { source: 'ml', target: 'supervised' },
  { source: 'ml', target: 'unsupervised' },
  { source: 'ml', target: 'feature-eng' },
  { source: 'ml', target: 'model-eval' },
  { source: 'ml', target: 'data-prep' },
  
  { source: 'deep-learning', target: 'tensorflow' },
  { source: 'deep-learning', target: 'pytorch' },
  { source: 'deep-learning', target: 'keras' },
  { source: 'deep-learning', target: 'cnn' },
  { source: 'deep-learning', target: 'rnn' },
  { source: 'deep-learning', target: 'transformer' },
  { source: 'deep-learning', target: 'gan' },
  { source: 'deep-learning', target: 'autoencoder' },
  
  { source: 'data-viz', target: 'matplotlib' },
  { source: 'data-viz', target: 'seaborn' },
  { source: 'data-viz', target: 'plotly' },
  
  { source: 'big-data', target: 'spark' },
  { source: 'big-data', target: 'hadoop' },
  { source: 'big-data', target: 'kafka' },
  
  { source: 'cloud', target: 'aws' },
  { source: 'cloud', target: 'gcp' },
  { source: 'cloud', target: 'azure' },
  
  { source: 'database', target: 'sql' },
  { source: 'database', target: 'mongodb' },
  { source: 'database', target: 'postgresql' },
  
  { source: 'data-eng', target: 'airflow' },
  { source: 'data-eng', target: 'kafka' },
  { source: 'data-eng', target: 'docker' },
  { source: 'data-eng', target: 'kubernetes' },
  
  { source: 'nlp', target: 'bert' },
  { source: 'nlp', target: 'gpt' },
  { source: 'nlp', target: 'transformer' },
  { source: 'nlp', target: 'nltk' },
  { source: 'nlp', target: 'spacy' },
  
  { source: 'cv', target: 'cnn' },
  { source: 'cv', target: 'opencv' },
  { source: 'cv', target: 'yolo' },
  
  { source: 'time-series', target: 'arima' },
  { source: 'time-series', target: 'prophet' },
  { source: 'time-series', target: 'lstm-ts' },
  
  { source: 'rl', target: 'q-learning' },
  { source: 'rl', target: 'policy-gradient' },
  { source: 'rl', target: 'actor-critic' },
  { source: 'rl', target: 'dqn' },
  
  { source: 'python', target: 'pandas' },
  { source: 'python', target: 'numpy' },
  { source: 'python', target: 'matplotlib' },
  { source: 'python', target: 'seaborn' },
  { source: 'python', target: 'sklearn' },
  { source: 'python', target: 'tensorflow' },
  { source: 'python', target: 'pytorch' },
  
  { source: 'stats', target: 'ml' },
  { source: 'stats', target: 'math' },
  
  // Tier 2 to Tier 3 connections
  { source: 'supervised', target: 'lightgbm' },
  { source: 'supervised', target: 'xgboost' },
  { source: 'supervised', target: 'sklearn' },
  { source: 'supervised', target: 'catboost' },
  { source: 'supervised', target: 'random-forest' },
  { source: 'supervised', target: 'svm' },
  { source: 'supervised', target: 'linear-reg' },
  { source: 'supervised', target: 'logistic-reg' },
  { source: 'supervised', target: 'decision-tree' },
  { source: 'supervised', target: 'naive-bayes' },
  { source: 'supervised', target: 'knn' },
  
  { source: 'unsupervised', target: 'kmeans' },
  { source: 'unsupervised', target: 'dbscan' },
  { source: 'unsupervised', target: 'hierarchical' },
  { source: 'unsupervised', target: 'pca' },
  { source: 'unsupervised', target: 'tsne' },
  { source: 'unsupervised', target: 'umap' },
  
  { source: 'model-eval', target: 'roc-auc' },
  { source: 'model-eval', target: 'f1-score' },
  { source: 'model-eval', target: 'confusion-matrix' },
  { source: 'model-eval', target: 'cross-val' },
  
  { source: 'feature-eng', target: 'one-hot' },
  { source: 'feature-eng', target: 'label-encoding' },
  { source: 'feature-eng', target: 'feature-selection' },
  { source: 'feature-eng', target: 'feature-scaling' },
  
  { source: 'data-prep', target: 'normalization' },
  { source: 'data-prep', target: 'standardization' },
  { source: 'data-prep', target: 'missing-data' },
  { source: 'data-prep', target: 'outlier-detection' },
  
  { source: 'optuna', target: 'grid-search' },
  { source: 'optuna', target: 'bayesian-opt' },
  
  { source: 'rnn', target: 'lstm' },
  
  { source: 'bert', target: 'word2vec' },
  { source: 'bert', target: 'glove' },
  { source: 'gpt', target: 'word2vec' },
  { source: 'gpt', target: 'fasttext' },
  
  // Cross-tier connections
  { source: 'pandas', target: 'sklearn' },
  { source: 'numpy', target: 'sklearn' },
  { source: 'numpy', target: 'pandas' },
  { source: 'matplotlib', target: 'seaborn' },
  
  { source: 'tensorflow', target: 'keras' },
  { source: 'pytorch', target: 'cnn' },
  { source: 'pytorch', target: 'rnn' },
  
  { source: 'sklearn', target: 'random-forest' },
  { source: 'sklearn', target: 'svm' },
  { source: 'sklearn', target: 'kmeans' },
  { source: 'sklearn', target: 'pca' },
];
